version: "2"
services:
  web:
    image: node:onbuild
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - auth-svc

  auth-svc:
    build: auth-svc
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      MYSQL_ENDPOINT: mysql
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: spi

  img-proc-api-svc:
    build: img-processor-svc/api-svc
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: spi

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: spi

  rabbitmq:
    image: rabbitmq:3.6
    ports:
      - "5672:5672"
