web:
  image: node:onbuild
  ports:
    - "8080:8080"
  volumes:
    - ./web:/usr/src/app
  links:
    - auth-svc

auth-svc:
  image: python:2-onbuild
  ports:
    - "8081:8081"
  volumes:
    - ./auth-svc:/usr/src/app
  command: bash -c "pip install -r /usr/src/app/requirements.txt;python /usr/src/app/auth-svc/auth-svc.py"
  links:
  - mysql

mysql:
  image: mysql:5.7
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: spi

