apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
  selector:
    app: mysql
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
