- name: install docker engine
  hosts: ubp-lab
  sudo: True
  environment:
    #http_proxy: http://proxy-us.intel.com:911
    #https_proxy: http://proxy-us.intel.com:911
    http_proxy: http://proxy.lab.ubp.edu.ar:3128
    https_proxy: http://proxy.lab.ubp.edu.ar:3128
  tasks:
    - apt: name=curl update_cache=yes

    - name: execute command curl to download docker engine installer
      command: curl -o install.sh -fsSL https://get.docker.com/

    - file: path=./install.sh mode="u+rwx,g+rx,o+rx"

    - name: execute command to run the installer script
      command: ./install.sh

    - service: name=docker state=restarted
